#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define PREFERRED_OVER 0
#define NOT_PREFERRED_OVER 1
#define INDIFFERENT_ON_C 2
#define DOMINATE 0
#define DOMINATED 1
#define INDIFFERENT 2
#define NOT_ENOUGH_INFO -1

#define QUESTION_SELECTION_ALGO 1
#define OBJECT_SIZE 5
#define CRITERIA_SIZE 3
#define CROUD_SIZE 21

#endif // CONSTANTS_H_INCLUDED
